import LinkComponent from "./components/LinkComponent";
import spotifyIcon from "./assets/_spotify.png";
import appleMusicIcon from "./assets/_apple.png";
import ytmusic from "./assets/_yt.png";
// import boomplay from "./assets/boomplay.png";
import bg from "/3.jpg";

import WaveformPlayer from "./components/WaveformPlayer";

import "./font.css";

const links = {
  spotify:
    "https://api.ffm.to/sl/e/ps/believer-clq?cd=eyJ1YSI6eyJ1YSI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjkuMC4wLjAgU2FmYXJpLzUzNy4zNiIsImJyb3dzZXIiOnsibmFtZSI6IkNocm9tZSIsInZlcnNpb24iOiIxMjkuMC4wLjAiLCJtYWpvciI6IjEyOSJ9LCJlbmdpbmUiOnsibmFtZSI6IkJsaW5rIiwidmVyc2lvbiI6IjEyOS4wLjAuMCJ9LCJvcyI6eyJuYW1lIjoiV2luZG93cyIsInZlcnNpb24iOiIxMCJ9LCJkZXZpY2UiOnt9LCJjcHUiOnsiYXJjaGl0ZWN0dXJlIjoiYW1kNjQifX0sImNsaWVudCI6eyJyaWQiOiJmN2M0YmZkNC1hMGRjLTRkZTktOWExZC04MjI0NjkxYWU3NTEiLCJzaWQiOiJkNDAyZWNjOC1jMTg5LTQ3ZGItYTY0NC02ODQzNGYyMjY3ZTAiLCJpcCI6IjEwMi4xNzYuMTEwLjE3IiwicmVmIjoiIiwiaG9zdCI6ImRpdHRvLmZtIiwibGFuZyI6ImVuLVVTIiwiaXBDb3VudHJ5IjoiR0gifSwiaXNXZWJwU3VwcG9ydGVkIjp0cnVlLCJpc0Zyb21FVSI6dHJ1ZSwiY291bnRyeUNvZGUiOm51bGwsImlzQm90IjpmYWxzZSwidXNlQWZmIjoib3JpZ2luIiwidmlkIjoiMWY0NWU3OWEtMjU1Yi00YjkwLWE1MGItZWI0YTkyMDNiM2Y3IiwiaWQiOiI2NzA4YzNjZjMyMDAwMDNhMDA1NTQyYTUiLCJwcnYiOmZhbHNlLCJpc1ByZVIiOnRydWUsInR6byI6bnVsbCwiY2giOm51bGwsImFuIjpudWxsLCJkZXN0VXJsIjoiaHR0cHM6Ly9hY2NvdW50cy5zcG90aWZ5LmNvbS9hdXRob3JpemU_Y2xpZW50X2lkPTY2ZDNjZGI0NDgwNzRhMGQ4OGU5YjA4YmFhZjJmM2Q3JnJlc3BvbnNlX3R5cGU9Y29kZSZyZWRpcmVjdF91cmk9aHR0cHMlM0ElMkYlMkZhcGkuZmZtLnRvJTJGd2ViaG9vayUyRnNwb3RpZnklMkZhdXRob3JpemUmc2NvcGU9dXNlci1yZWFkLXByaXZhdGUlMjB1c2VyLXJlYWQtYmlydGhkYXRlJTIwdXNlci1yZWFkLWVtYWlsJTIwdXNlci1saWJyYXJ5LW1vZGlmeSUyMHVzZXItbGlicmFyeS1yZWFkJTIwdXNlci1yZWFkLXJlY2VudGx5LXBsYXllZCUyMHVzZXItZm9sbG93LXJlYWQlMjB1c2VyLWZvbGxvdy1tb2RpZnklMjB1c2VyLXRvcC1yZWFkJTIwcGxheWxpc3QtbW9kaWZ5LXB1YmxpYyUyMHBsYXlsaXN0LXJlYWQtcHJpdmF0ZSUyMHBsYXlsaXN0LW1vZGlmeS1wcml2YXRlJnN0YXRlPWV5SmtZa3hwYm10SlpDSTZJalkzTURoak0yTm1Nekl3TURBd00yRXdNRFUxTkRKaE5TSXNJbUZqZEdsdmJsUjVjR1VpT201MWJHd3NJbU4wWVNJNklsQnlaUzFUWVhabElpd2lkWE5sY2tOdmRXNTBjbmtpT2lKSFNDSXNJbk5vYjNKMFNXUWlPaUppWld4cFpYWmxjaTFqYkhFaUxDSmtiMjFoYVc0aU9pSm9kSFJ3Y3pvdkwyUnBkSFJ2TG1adElpd2ljMlZ5ZG1salpVNWhiV1VpT2lKemNHOTBhV1o1SWl3aWNISnZaSFZqZENJNkluTnRZWEowYkdsdWF5SXNJbkpsWkdseVpXTjBWWEpwSWpvaWFIUjBjSE02THk5a2FYUjBieTVtYlM5aVpXeHBaWFpsY2kxamJIRXZjSEpsYzJGMlpXTmhiR3hpWVdOcklpd2labUZzYkdKaFkydFZjbXdpT201MWJHd3NJbWx6VUhKbFVtVnNaV0Z6WlNJNmRISjFaU3dpYVhOR2RYUjFjbVZTWld4bFlYTmxJanAwY25WbExDSmhjblJwYzNSSlpDSTZJalZqWVROaU9EY3lNR1V3TURBd01HSmhNemxpWXpSbE1pSXNJbUZ5ZEdsemRFOTNibVZ5SWpvaU5XTTFNR0kxTVdReE5EQXdNREF4T1RBd05qZzJPRGt4SWl3aVlXTjBhVzl1U1dRaU9tNTFiR3dzSW1selJuSnZiVVZWSWpwbVlXeHpaU3dpYkdsdWExUjVjR1VpT201MWJHd3NJblZ6WlhKSlVDSTZJakV3TWk0eE56WXVNVEV3TGpFM0lpd2ljbVYzWVhKa1ZYTmxja2xrSWpwdWRXeHNMQ0p5WldabGNuSmhiRWxrSWpwdWRXeHNMQ0oxZFdsa0lqb2lNV1kwTldVM09XRXRNalUxWWkwMFlqa3dMV0UxTUdJdFpXSTBZVGt5TUROaU0yWTNJbjA9Iiwic3J2YyI6InNwb3RpZnkiLCJwcm9kdWN0Ijoic21hcnRsaW5rIiwic2hvcnRJZCI6ImJlbGlldmVyLWNscSIsImlzQXV0aG9yaXphdGlvblJlcXVpcmVkIjp0cnVlLCJvd25lciI6IjVjNTBiNTFkMTQwMDAwMTkwMDY4Njg5MSIsInRlbmFudCI6IjVkMmMyOTYzZjBkNTFlZWJkMjRlNzc4NyIsImFyIjoiNWNhM2I4NzIwZTAwMDAwYmEzOWJjNGUyIiwiaXNTaG9ydExpbmsiOmZhbHNlfQ",
  apple:
    "https://api.ffm.to/sl/e/ps/believer-clq?cd=eyJ1YSI6eyJ1YSI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjkuMC4wLjAgU2FmYXJpLzUzNy4zNiIsImJyb3dzZXIiOnsibmFtZSI6IkNocm9tZSIsInZlcnNpb24iOiIxMjkuMC4wLjAiLCJtYWpvciI6IjEyOSJ9LCJlbmdpbmUiOnsibmFtZSI6IkJsaW5rIiwidmVyc2lvbiI6IjEyOS4wLjAuMCJ9LCJvcyI6eyJuYW1lIjoiV2luZG93cyIsInZlcnNpb24iOiIxMCJ9LCJkZXZpY2UiOnt9LCJjcHUiOnsiYXJjaGl0ZWN0dXJlIjoiYW1kNjQifX0sImNsaWVudCI6eyJyaWQiOiJmN2M0YmZkNC1hMGRjLTRkZTktOWExZC04MjI0NjkxYWU3NTEiLCJzaWQiOiJkNDAyZWNjOC1jMTg5LTQ3ZGItYTY0NC02ODQzNGYyMjY3ZTAiLCJpcCI6IjEwMi4xNzYuMTEwLjE3IiwicmVmIjoiIiwiaG9zdCI6ImRpdHRvLmZtIiwibGFuZyI6ImVuLVVTIiwiaXBDb3VudHJ5IjoiR0gifSwiaXNXZWJwU3VwcG9ydGVkIjp0cnVlLCJpc0Zyb21FVSI6dHJ1ZSwiY291bnRyeUNvZGUiOm51bGwsImlzQm90IjpmYWxzZSwidXNlQWZmIjoib3JpZ2luIiwidmlkIjoiMWY0NWU3OWEtMjU1Yi00YjkwLWE1MGItZWI0YTkyMDNiM2Y3IiwiaWQiOiI2NzA4YzNjZjMyMDAwMDNhMDA1NTQyYTUiLCJwcnYiOmZhbHNlLCJpc1ByZVIiOnRydWUsInR6byI6bnVsbCwiY2giOm51bGwsImFuIjpudWxsLCJkZXN0VXJsIjoiaHR0cHM6Ly9hcGkuZmZtLnRvL3dlYmhvb2svYXBwbGUvYXV0aG9yaXplP3N0YXRlPWV5SmtZa3hwYm10SlpDSTZJalkzTURoak0yTm1Nekl3TURBd00yRXdNRFUxTkRKaE5TSXNJbUZqZEdsdmJsUjVjR1VpT201MWJHd3NJbU4wWVNJNklsQnlaUzFCWkdRaUxDSjFjMlZ5UTI5MWJuUnllU0k2SWtkSUlpd2ljMmh2Y25SSlpDSTZJbUpsYkdsbGRtVnlMV05zY1NJc0ltUnZiV0ZwYmlJNkltaDBkSEJ6T2k4dlpHbDBkRzh1Wm0waUxDSnpaWEoyYVdObFRtRnRaU0k2SW1Gd2NHeGxJaXdpY0hKdlpIVmpkQ0k2SW5OdFlYSjBiR2x1YXlJc0luSmxaR2x5WldOMFZYSnBJam9pYUhSMGNITTZMeTlrYVhSMGJ5NW1iUzlpWld4cFpYWmxjaTFqYkhFdmNISmxjMkYyWldOaGJHeGlZV05ySWl3aVptRnNiR0poWTJ0VmNtd2lPbTUxYkd3c0ltbHpVSEpsVW1Wc1pXRnpaU0k2ZEhKMVpTd2lhWE5HZFhSMWNtVlNaV3hsWVhObElqcDBjblZsTENKaGNuUnBjM1JKWkNJNklqVmpZVE5pT0RjeU1HVXdNREF3TUdKaE16bGlZelJsTWlJc0ltRnlkR2x6ZEU5M2JtVnlJam9pTldNMU1HSTFNV1F4TkRBd01EQXhPVEF3TmpnMk9Ea3hJaXdpWVdOMGFXOXVTV1FpT201MWJHd3NJbWx6Um5KdmJVVlZJanBtWVd4elpTd2liR2x1YTFSNWNHVWlPbTUxYkd3c0luVnpaWEpKVUNJNklqRXdNaTR4TnpZdU1URXdMakUzSWl3aWNtVjNZWEprVlhObGNrbGtJanB1ZFd4c0xDSnlaV1psY25KaGJFbGtJanB1ZFd4c0xDSjFkV2xrSWpvaU1XWTBOV1UzT1dFdE1qVTFZaTAwWWprd0xXRTFNR0l0WldJMFlUa3lNRE5pTTJZM0luMD0iLCJzcnZjIjoiYXBwbGUiLCJwcm9kdWN0Ijoic21hcnRsaW5rIiwic2hvcnRJZCI6ImJlbGlldmVyLWNscSIsImlzQXV0aG9yaXphdGlvblJlcXVpcmVkIjp0cnVlLCJvd25lciI6IjVjNTBiNTFkMTQwMDAwMTkwMDY4Njg5MSIsInRlbmFudCI6IjVkMmMyOTYzZjBkNTFlZWJkMjRlNzc4NyIsImFyIjoiNWNhM2I4NzIwZTAwMDAwYmEzOWJjNGUyIiwiaXNTaG9ydExpbmsiOmZhbHNlfQ",
  yt: "https://api.ffm.to/sl/e/ps/believer-clq?cd=eyJ1YSI6eyJ1YSI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjkuMC4wLjAgU2FmYXJpLzUzNy4zNiIsImJyb3dzZXIiOnsibmFtZSI6IkNocm9tZSIsInZlcnNpb24iOiIxMjkuMC4wLjAiLCJtYWpvciI6IjEyOSJ9LCJlbmdpbmUiOnsibmFtZSI6IkJsaW5rIiwidmVyc2lvbiI6IjEyOS4wLjAuMCJ9LCJvcyI6eyJuYW1lIjoiV2luZG93cyIsInZlcnNpb24iOiIxMCJ9LCJkZXZpY2UiOnt9LCJjcHUiOnsiYXJjaGl0ZWN0dXJlIjoiYW1kNjQifX0sImNsaWVudCI6eyJyaWQiOiJmN2M0YmZkNC1hMGRjLTRkZTktOWExZC04MjI0NjkxYWU3NTEiLCJzaWQiOiJkNDAyZWNjOC1jMTg5LTQ3ZGItYTY0NC02ODQzNGYyMjY3ZTAiLCJpcCI6IjEwMi4xNzYuMTEwLjE3IiwicmVmIjoiIiwiaG9zdCI6ImRpdHRvLmZtIiwibGFuZyI6ImVuLVVTIiwiaXBDb3VudHJ5IjoiR0gifSwiaXNXZWJwU3VwcG9ydGVkIjp0cnVlLCJpc0Zyb21FVSI6dHJ1ZSwiY291bnRyeUNvZGUiOm51bGwsImlzQm90IjpmYWxzZSwidXNlQWZmIjoib3JpZ2luIiwidmlkIjoiMWY0NWU3OWEtMjU1Yi00YjkwLWE1MGItZWI0YTkyMDNiM2Y3IiwiaWQiOiI2NzA4YzNjZjMyMDAwMDNhMDA1NTQyYTUiLCJwcnYiOmZhbHNlLCJpc1ByZVIiOnRydWUsInR6byI6bnVsbCwiY2giOm51bGwsImFuIjpudWxsLCJkZXN0VXJsIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL3YyL2F1dGg_YWNjZXNzX3R5cGU9b2ZmbGluZSZpbmNsdWRlX2dyYW50ZWRfc2NvcGVzPXRydWUmc3RhdGU9ZXlKa1lreHBibXRKWkNJNklqWTNNRGhqTTJObU16SXdNREF3TTJFd01EVTFOREpoTlNJc0ltRmpkR2x2YmxSNWNHVWlPbTUxYkd3c0ltTjBZU0k2SWxCeVpTMVRZWFpsSWl3aWRYTmxja052ZFc1MGNua2lPaUpIU0NJc0luTm9iM0owU1dRaU9pSmlaV3hwWlhabGNpMWpiSEVpTENKa2IyMWhhVzRpT2lKb2RIUndjem92TDJScGRIUnZMbVp0SWl3aWMyVnlkbWxqWlU1aGJXVWlPaUo1YjNWMGRXSmxiWFZ6YVdNaUxDSndjbTlrZFdOMElqb2ljMjFoY25Sc2FXNXJJaXdpY21Wa2FYSmxZM1JWY21raU9pSm9kSFJ3Y3pvdkwyUnBkSFJ2TG1adEwySmxiR2xsZG1WeUxXTnNjUzl3Y21WellYWmxZMkZzYkdKaFkyc2lMQ0ptWVd4c1ltRmphMVZ5YkNJNmJuVnNiQ3dpYVhOUWNtVlNaV3hsWVhObElqcDBjblZsTENKcGMwWjFkSFZ5WlZKbGJHVmhjMlVpT25SeWRXVXNJbUZ5ZEdsemRFbGtJam9pTldOaE0ySTROekl3WlRBd01EQXdZbUV6T1dKak5HVXlJaXdpWVhKMGFYTjBUM2R1WlhJaU9pSTFZelV3WWpVeFpERTBNREF3TURFNU1EQTJPRFk0T1RFaUxDSmhZM1JwYjI1SlpDSTZiblZzYkN3aWFYTkdjbTl0UlZVaU9tWmhiSE5sTENKc2FXNXJWSGx3WlNJNmJuVnNiQ3dpZFhObGNrbFFJam9pTVRBeUxqRTNOaTR4TVRBdU1UY2lMQ0p5WlhkaGNtUlZjMlZ5U1dRaU9tNTFiR3dzSW5KbFptVnljbUZzU1dRaU9tNTFiR3dzSW5WMWFXUWlPaUl4WmpRMVpUYzVZUzB5TlRWaUxUUmlPVEF0WVRVd1lpMWxZalJoT1RJd00ySXpaamNpZlElM0QlM0QmcmVzcG9uc2VfdHlwZT1jb2RlJmNvbnNlbnQ9UGxlYXNlJTIwYWxsb3cmcHJvbXB0PWNvbnNlbnQmc2NvcGU9aHR0cHMlM0ElMkYlMkZ3d3cuZ29vZ2xlYXBpcy5jb20lMkZhdXRoJTJGeW91dHViZSUyMGh0dHBzJTNBJTJGJTJGd3d3Lmdvb2dsZWFwaXMuY29tJTJGYXV0aCUyRnVzZXJpbmZvLnByb2ZpbGUlMjBodHRwcyUzQSUyRiUyRnd3dy5nb29nbGVhcGlzLmNvbSUyRmF1dGglMkZ1c2VyaW5mby5lbWFpbCUyMGh0dHBzJTNBJTJGJTJGd3d3Lmdvb2dsZWFwaXMuY29tJTJGYXV0aCUyRm11c2ljJmNsaWVudF9pZD03Njc4Mjc5MjMwMjctaGdramFmamJqaTEydXJ1dmxpNXQ5cWxtZGF0a3B2MjIuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20mcmVkaXJlY3RfdXJpPWh0dHBzJTNBJTJGJTJGYXBpLmZmbS50byUyRndlYmhvb2slMkZ5b3V0dWJlJTJGYXV0aG9yaXplIiwic3J2YyI6InlvdXR1YmVtdXNpYyIsInByb2R1Y3QiOiJzbWFydGxpbmsiLCJzaG9ydElkIjoiYmVsaWV2ZXItY2xxIiwiaXNBdXRob3JpemF0aW9uUmVxdWlyZWQiOnRydWUsIm93bmVyIjoiNWM1MGI1MWQxNDAwMDAxOTAwNjg2ODkxIiwidGVuYW50IjoiNWQyYzI5NjNmMGQ1MWVlYmQyNGU3Nzg3IiwiYXIiOiI1Y2EzYjg3MjBlMDAwMDBiYTM5YmM0ZTIiLCJpc1Nob3J0TGluayI6ZmFsc2V9",
};

function App() {
  return (
    <main
      style={{
        backgroundImage: `url(${bg})`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        height: "100vh",
      }}
      className="w-screen min-h-screen flex h-screen flex-col items-center justify-center"
    >
      <div className="w-[380px] flex rounded-lg flex-col py-2 my-2">
        <p className="flex justify-center text-center text-2xl font-semibold text-orange-500">
          {" "}
          Cl!Q ft. Yaw Palmer BELIEVER
        </p>
      </div>
      <div className="w-[380px] rounded-lg bg-gray-100 flex flex-col py-2">
        <div>
          <div className="text-center font-semibold mt-2 text-xl"></div>
          <div className="mt-4">
            <LinkComponent
              icon={spotifyIcon}
              link={links.spotify}
              imagew="100"
            />
            <LinkComponent
              icon={appleMusicIcon}
              link={links.apple}
              imagew="150"
            />
            <LinkComponent icon={ytmusic} link={links.yt} imagew="150" />
            {/* <LinkComponent icon={boomplay} name={"Boomplay"} link={"#"} /> */}
          </div>
        </div>

        <div className="my-4">
          <WaveformPlayer />
        </div>
      </div>
    </main>
  );
}

export default App;
